// Bundles api-src/*.ts into plain, self-contained JavaScript in api/ for Vercel.
// The output is committed so the hosted functions never depend on how a host
// compiles TypeScript. Re-run with: npm run build:api
import { build } from 'esbuild';
import { readdirSync } from 'node:fs';

const entries = readdirSync('api-src').filter((f) => f.endsWith('.ts')).map((f) => `api-src/${f}`);
await build({
  entryPoints: entries,
  outdir: 'api',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'none',
  banner: { js: '// Generated by scripts/build-api.mjs from api-src/ and server/. Do not edit.' },
  logLevel: 'info',
});
